config/routes.rb
Rails.application.routes.draw do
  get 'static/index'
  get 'profile/update'
  resources :events

  devise_for :users, exclude_routes: %w[edit_user_registration]

  #root to: 'events#index'
  #get '/index', to: 'static#index'
  root to: 'static#index'
  get '/welcome', to: 'static#welcome', as: 'welcome'

  resources :products, only: %i[create destroy show update]
  get '/products/:id/eaters', to: 'products#eaters'
  post '/products/:id/eaters', to: 'products#update_eaters'

  get '/join/:id', to: 'members#join', as: 'join'
  get '/leave/:id', to: 'members#leave', as: 'leave'
  delete '/leave/:id/:user_id', to: 'members#remove_member', as: 'remove_member'
  post '/bots/:id', to: 'members#add_bot', as: 'add_bot'

  put 'products/:id/eaters', to: 'products#add_eater', as: 'add_eater'
  delete 'products/:id/eaters', to: 'products#delete_eater', as: 'delete_eater'
  post 'products/:id/change_eater', to: 'products#change_eater', as: 'change_eater'
  # post '/products/complete', to: 'products#addition_complete', as: 'products_complete'

  get '/profile', to: 'profile#index', as: 'profile'
  post '/profile', to: 'profile#new'
  patch '/profile', to: 'profile#update'
  patch '/profile/password', to: 'profile#change_password', as: 'change_password'

  get '/events/:id/results', to: 'events#results', as: 'event_results'
  post '/events/:id/change_status', to: 'events#change_status', as: 'change_status'

  post '/quest', to: 'events#create_quest', as: 'quest'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  # Fields: name, description, evented_at, user_id, join_id
  belongs_to :user
  has_many :products, dependent: :delete_all
  has_and_belongs_to_many :members, class_name: 'User'
  enum status: { active: 0, archived: 1 }

  validates :name, presence: true
  validates :join_id, uniqueness: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy results change_status]
  before_action :authenticate_user!, except: %i[create_quest show edit update results ]
  before_action :only_members, only: %i[destroy ]

  # GET /events or /events.json
  def index
    @events = []
    @events = (current_user.events.to_a + current_user.member_of.to_a).uniq

    @active_events = (current_user.events.active.to_a + current_user.member_of.active.to_a).uniq
    @archived_events = (current_user.events.archived.to_a + current_user.member_of.archived.to_a).uniq

  end

  # GET /events/1 or /events/1.json
  def show
    @bot = User.new
    @product = Product.new
    @products = @event.products
    @is_member = is_member?

    if !@event.isPublic && !@is_member
      render '/events/not_a_member'
    end

    prepare_members

    @owner = user_signed_in? ? @event.user == current_user : false
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @is_member = is_member?
  end

  # POST /events or /events.json
  def create
    # @event = Event.new(event_params)
    @event = current_user.events.new(event_params)
    @event.join_id = (0...8).map { rand(65..90).chr }.join

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /events/quest
  def create_quest
    quest_email = SecureRandom.hex(20) + '@quest.com'
    quest_password = SecureRandom.base64(12)
    quest = User.new(email: quest_email, password: quest_password, isQuest: true )
    quest.skip_confirmation!
    quest.save!

    event_params = {
      name: 'Просто по пиву',
      description: 'Для такого специальный повод не нужен',
      evented_at: Date.today,
      isPublic: true
    }
    @event = quest.events.new(event_params)
    @event.join_id = (0...8).map { rand(65..90).chr }.join      # наследие первых версий. Сейчас join_id не нужен, но пока не убираю
    if @event.save
      redirect_to @event, notice: 'Добро пожаловать!'
    else
      redirect_to welcome_path, alert: 'Что-то пошло не так ;-('
    end

  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Событие было успешно обновлено' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Событие было успешно удалено' }
      format.json { head :no_content }
    end
  end

  # GET /events/:id/results
  def results
    prepare_members

    @results = []
    @members.each do |member|
      # Это объект с полями:
      # user - объект ListItem
      # spent - сколько потратил покупая продукты
      # debt - сколько остался должен после того, как съел продукты
      result = {}
      result['user'] = member
      result['spent'] = @event.products.where({ buyer_id: member.id }).sum(:price)

      debt = 0
      @event.products.each do |product|
        count = 0
        if Eater.where({ product_id: product.id, user_id: member.id }).length > 0
          # Убеждаемся, что пользователь вообще ел данный продукт

          if product.total
            # Если продукт исчисляемый
            count = Eater.where({ product_id: product.id }).length
            part_user = Eater.where({ product_id: product.id, user_id: member.id }).length
            debt += (product.price * part_user) / count
          else
            # Если продукт неисчисляемый

            # считаем сколько всего человек ело данный продукт
            count = Eater.where({ product_id: product.id }).select(:user_id).distinct.length
            debt += product.price / count
          end
        end
      end
      result['debt'] = debt

      @results << result
    end
  end

  # POST /events/:id/change_status
  def change_status
    if @event.user == current_user
      @event.active? ? @event.archived! : @event.active!
      redirect_to events_path, notice: 'Статус мероприятия изменен'
    else
      redirect_to event_path(@event), alert: 'Вы не организатор этого мероприятия'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find_by_id(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.fetch(:event, {}).permit(:name, :description, :evented_at, :isPublic)
  end

  def only_members
    #prepare_members
    # Если пользователь не участник встречи - перенаправляем на главную,
    # чтобы не видел результаты
    redirect_to root_path unless is_member?
  end

  def prepare_members
    @members = []
    unless @event.user.isQuest
      @members << @event.user
    end
    @members = (@members + @event.members.to_a).uniq
  end

  def is_member?
    result = false
    if user_signed_in?
      prepare_members
      result = @members.include?(current_user)
    end

    return result
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="row w-100">
  <div class="card">
    <div class="card-body">
      <%= form_with(model: event, html: {class: 'form'}) do |form| %>


        <div class="form-control">
          <%= form.label :name, 'Придумай название:', class: 'form-label' %>
          <%= form.text_field :name, required: true,
                              autofocus: true,
                              class: 'form-input'
          %>
        </div>

        <div class="form-control">
          <%= form.label :evented_at, 'Когда пьем:', class: 'form-label' %>
          <%= form.date_field :evented_at, value: form.object.try(:strftime,"%d/%m/%Y"), class: 'form-input' %>
        </div>

        <div class="form-control">
          <%= form.label :description, 'Какой повод:', class: 'form-label' %>
          <%= form.text_area :description, class: 'form-input' %>
        </div>

        <% if @is_member %>
          <div class="form-control">
            <%= form.label :isPublic, 'Публичное мероприятие:', class: 'form-label' %>
            <%= form.check_box :isPublic, class: 'form-checkbox' %>
          </div>
        <% end %>

        <div class="form-buttons">
          <%= form.submit 'Сохранить', class: 'form-button form-apply' %>
          <%= link_to 'Отмена', cancel_path, class: 'form-button form-cancel' %>
        </div>


        <% if event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
              <% event.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/events/_index_list.html.erb
<% if events.length > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th>
          Название
        </th>
        <th>
          Повод
        </th>
        <th>
          Дата
        </th>
      </tr>
    </thead>
    <tbody>
      <% events.each do |event| %>
        <tr>
          <td >
            <%= link_to event.name, event, class: 'link' %>
          </td>
          <td>
            <%= event.description %>
          </td>
          <td>
            <%= I18n.l(event.evented_at.to_time, :format => '%e %B %Y') if event.evented_at %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
    <div class="fields-no-data">
      Событий нет
    </div>
<% end %>

app/views/events/_products_form.html.erb
<%= form_with(model: @product, url: products_path, html: {class: 'add-form'}, local: false) do |form| %>
  <div class="add-form-container">
    <%= form.text_field :name, required: true,
                        placeholder: 'Название',
                        class: 'products-form-input products-form_name'
    %>

    <%= form.number_field :price, min: 0, max: 100000,
                          placeholder: 'Стоимость',
                          class: 'products-form-input products-form_price'
    %>

    <%= form.collection_select :buyer_id, @members, :id, :username,
                               {prompt: 'Покупатель'},
                               {class: 'products-form-input products-form_buyer'}
    %>

    <%= form.hidden_field :event_id, value: @event.id %>

    <%= form.submit "Добавить", class: 'add-bot-submit' %>
  </div>

  <input type="checkbox" id="countable" name="countable"/>
  <label for="countable" class="products-form_text">Требует поштучного учета</label>

  <div class="add-form-hidden" id="hidden">
    <%= form.number_field :total, min: 0, max: 100000,
                          placeholder: 'Количество*',
                          class: 'products-form-input products-form_price'
    %>

    <p class="products-form_comment">
      * Количество продукта надо указывать, если важно разделить его не поровну между всеми. Пример: <br>
      - Вы купили 10 бутылок пива. <br>
      - Иван выпил 2 бутылку<br>
      - Денис не стал пить пиво<br>
      - Саша выпил 8 штук. <br>
      В этом случае указывает, что было куплено 10 бутылок и затем каждый отмечает у себя то количество,
      которое на самом деле выпил. В результате Иван оплатит 2/10 стоимости всего пива, Денис ничего не заплатит,
      а Саша заплатит 8/10.
    </p>
  </div>
<% end %>

<%= javascript_pack_tag 'events/products-form' %>

app/views/events/edit.html.erb
<div class="row w-100">
  <div class="card bg-gray1">
    <h1 class="title events-title">
      <%= link_to event_path(@event), class: 'back-link' do %>
        <i class="fa-regular fa-circle-left"></i>
      <% end %>
      Изменить мероприятие
    </h1>
  </div>
</div>


<%= render 'form', event: @event, cancel_path: event_path(@event) %>

app/views/events/index.html.erb
  <div class="row w-100">
    <div class="card bg-gray1">
      <div class="row w-100 jc-sb">
        <h1 class="title events-title">Мероприятия</h1>

        <%= link_to new_event_path, class: "button" do %>
          <i class="fa-solid fa-circle-plus"></i>
        <% end %>
      </div>
    </div>
  </div>


  <div class="row w-100">
    <div class="card">
      <div class="card-header">
        <div>
          <a href="#" id="set-active" class="status-links status-links_active">
            Активные
          </a>
          <a href="#" id="set-archive" class="status-links">
            Архив
          </a>
        </div>
      </div>
      <div class="card-body">
        <div id="active" class="status-links_body">
          <%= render 'events/index_list', events: @active_events %>
        </div>

        <div id="archive" class="status-links_body archived">
          <%= render 'events/index_list', events: @archived_events %>
        </div>
      </div>
    </div>
  </div>

<%= javascript_pack_tag 'events/index-tabs' %>

app/views/events/new.html.erb
<div class="row w-100">
  <div class="card bg-gray1">
    <div class="row w-100 jc-sb">
      <h1 class="title events-title">
        <%= link_to events_path, class: 'back-link' do %>
          <i class="fa-regular fa-circle-left"></i>
        <% end %>
        Новое мероприятие
      </h1>
    </div>
  </div>
</div>

<%= render 'form', event: @event, cancel_path: events_path %>

app/views/events/not_a_member.html.erb
<div class="row w-100">
  <div class="card bg-gray1">
    <div class="row w-100 jc-sb">
      <h1 class="title events-title">
        <i class="fa-solid fa-xmark"></i>
        Мероприятие закрытое, а вы не участник
      </h1>
      <%= link_to 'Назад', welcome_path, class: "title-link" %>
    </div>
  </div>
</div>

app/views/events/results.html.erb
<div class="row w-100">
  <div class="card bg-gray1">
    <div class="row w-100 jc-sb">
      <h1 class="title events-title">
        <%= link_to event_path(@event), class: 'back-link' do %>
          <i class="fa-regular fa-circle-left"></i>
        <% end %>
        <%= @event.name %> (итоги)
      </h1>
    </div>
  </div>
</div>

<% cols = []
   rows = []
   @results.each do |result|
     if result['spent'] > result['debt']
       cols << result
     else
       rows << result
     end
   end %>

<div class="row w-100">
  <div class="card">
    <div class="card-body">
      <div class="table-container">
        <table class="table">
          <thead>
          <tr>
            <th rowspan="2">Кто переводит</th>
            <th colspan=<%= cols.length %>>
              Кому переводят
            </th>
          </tr>

          <tr>
            <% cols.each do |col| %>
              <% col['need_money'] = col['spent'] - col['debt'] %>
              <td><%= col['user'].username %></td>
            <% end %>
          </tr>
          </thead>
          <tbody>
          <% rows.each do |row| %>
            <% debug = {} %>
            <% current_debt = row['debt'] - row['spent'] %>
            <tr>
              <td>
                <%= row['user'].username %>
              </td>
              <% cols.each do |col| %>
                <td>
                  <% if current_debt == 0 %>
                    0
                  <% elsif col['need_money'] == 0%>
                    0
                  <% elsif current_debt <= col['need_money'] %>
                    <%= number_to_currency(current_debt, unit: 'руб.', format: "%n %u") %>
                    <% col['need_money'] = col['need_money'] - current_debt %>
                    <% current_debt = 0 %>
                  <% else %>
                    <%= number_to_currency(col['need_money'], unit: 'руб.', format: "%n %u") %>
                    <% current_debt = current_debt - col['need_money'] %>
                    <% col['need_money'] = 0 %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

    </div>
    <div class="card-footer">
      <% if @event.user == current_user %>
        <%= link_to  change_status_path, method: :post, class: 'result-button' do %>
          <% if @event.active? %>
            Отправить мероприятие в архив
          <% else %>
            Сделать мероприятие опять активным
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="row w-100">
  <div class="card bg-gray1">
    <div class="row w-100 jc-sb">
      <h1 class="title events-title">
        <% if user_signed_in? %>
          <%= link_to events_path, class: 'back-link' do %>
            <i class="fa-regular fa-circle-left"></i>
          <% end %>
        <% end %>
        <%= @event.name %>
        <% if @event.archived? %>
          (архив)
        <% end %>
      </h1>

      <div class="title-rightblock">
        <%= link_to 'Изменить', edit_event_path(@event), class: "title-link" %>

        <% if @owner %>
          <%= link_to 'Удалить', event_path(@event), class: 'title-link delete-link',
                      method: :delete,
                      data: { confirm: 'Вы уверены, что хотите удалить такое мероприятие?' }
          %>
        <% end %>

      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="w-50">
    <div class="card">
      <div class="card-header">
        Информация
      </div>
      <div class="card-body">
        <div class="event-reason">
          <p class="event-fieldname">Повод:</p>
          <p class="event-fieldvalue"><%= @event.description %></p>
        </div>
        <div class="event-reason">
          <p class="event-fieldname">Дата:</p>
          <p class="event-fieldvalue">
            <%= I18n.l(@event.evented_at.to_time, :format => '%e %B %Y') if @event.evented_at %>
          </p>
        </div>
        <div class="event-reason">
          <p class="event-fieldname">
            Тип:
          </p>
          <p class="event-fieldvalue">
            <% if @event.isPublic %>
              Открытое мероприятие
            <% else %>
              Закрытое мероприятие
            <% end %>
          </p>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to 'Подвести итоги', event_results_path(@event), class: 'result-link' %>
      </div>
    </div>
  </div>
  <div class="w-50">
    <div class="card">
      <div class="card-header">
        Участники
        <% if user_signed_in? && !@is_member %>
          <%=  link_to 'Участвовать', join_path(@event), class: 'leave-link' %>
        <% end %>
      </div>
      <div class="card-body">
<!--        <div class="join">-->
<!--          <p class="join-title">Пригласить:</p>-->
          <%#= link_to join_url(@event.join_id), "#", class: 'join-link', id: 'join-link' %>

<!--          <div class="join-confirm" id="join-confirm">-->
<!--            Скопировано!-->
<!--          </div>-->
<!--        </div>-->
        <div class="members">
          <% if @members.length == 0 %>
            <p class="add-bot-subheader">
              Пока участников нет
            </p>
          <% end %>
          <ul>
            <% @members.each do |member| %>
              <li class="members-item">
                <%= member.username %>

                <% if member == @event.user %>
                  (Организатор)
                <% else %>
                  <%# if current_user == @event.user %>
                    <%= link_to remove_member_path(@event, member.id),
                                method: :delete, class: 'remove-link' do %>
                    <i class="fa-solid fa-trash"></i>
                    <% end %>
                  <%# end %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="card-footer">
        <%= form_with(model: @bot, url: add_bot_path, html: {class: 'add-bot'}) do |form| %>
          <div class="add-bot-header">
            Добавьте участника-бота
          </div>
          <p class="add-bot-subheader">
            (заглушка, вместо живого человека):
          </p>
          <div class="add-bot-container">
            <%= form.text_field :username, required: true,
                                placeholder: 'Имя бота',
                                class: 'add-bot-input'
            %>

            <%= form.submit 'Добавить', class: 'add-bot-submit' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render '/products/products', products: @products %>


<%#= javascript_pack_tag 'events/join' %>