config/routes.rb
Rails.application.routes.draw do
  get 'static/index'
  get 'profile/update'
  resources :events

  devise_for :users, exclude_routes: %w[edit_user_registration]

  #root to: 'events#index'
  #get '/index', to: 'static#index'
  root to: 'static#index'
  get '/welcome', to: 'static#welcome', as: 'welcome'

  resources :products, only: %i[create destroy show update]
  get '/products/:id/eaters', to: 'products#eaters'
  post '/products/:id/eaters', to: 'products#update_eaters'

  get '/join/:id', to: 'members#join', as: 'join'
  get '/leave/:id', to: 'members#leave', as: 'leave'
  delete '/leave/:id/:user_id', to: 'members#remove_member', as: 'remove_member'
  post '/bots/:id', to: 'members#add_bot', as: 'add_bot'

  put 'products/:id/eaters', to: 'products#add_eater', as: 'add_eater'
  delete 'products/:id/eaters', to: 'products#delete_eater', as: 'delete_eater'
  post 'products/:id/change_eater', to: 'products#change_eater', as: 'change_eater'
  # post '/products/complete', to: 'products#addition_complete', as: 'products_complete'

  get '/profile', to: 'profile#index', as: 'profile'
  post '/profile', to: 'profile#new'
  patch '/profile', to: 'profile#update'
  patch '/profile/password', to: 'profile#change_password', as: 'change_password'

  get '/events/:id/results', to: 'events#results', as: 'event_results'
  post '/events/:id/change_status', to: 'events#change_status', as: 'change_status'

  post '/quest', to: 'events#create_quest', as: 'quest'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :buyer, foreign_key: :buyer_id, class_name: 'User'
  belongs_to :event
  # has_and_belongs_to_many :eaters, class_name: 'ListItem'

  validates :name, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: %i[create destroy show eaters update_eaters update]
  before_action :set_product, only: %i[destroy change_eater add_eater delete_eater show update eaters update_eaters]

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        @event = @product.event
        prepare_members
        # Делаем так, что новый продукт ели все участники
        @members.each do |member|
          Eater.create(product_id: @product.id, user_id: member.id)
        end

        @event = @product.event
        prepare_for_form
        @products = @event.products
        format.js { render template: '/products/show_table' }
      else
        redirect_to event_path(product_params.event_id)
      end
    end
  end

  # DELETE /products/:id
  def destroy
    Eater.where({ product_id: @product.id }).destroy_all
    @product.destroy
    @products = @event.products
    prepare_members
    respond_to do |format|
      format.html { redirect_to event_path(@event), notice: 'Продукт удален' }
      format.json { head :no_content }
      format.js { render template: '/products/show_table' }
    end
  end

  # POST /products/:id/eater
  def change_eater
    if params[:ate] == "true"
      Eater.create(product_id: @product.id, user_id: current_user.id)
    else
      Eater.where({ product_id: @product.id, user_id: current_user.id }).destroy_all
    end
    @products = @event.products
    @product = Product.new
    prepare_members
    respond_to do |format|
      format.js { render template: '/products/show_table' }
    end
  end

  # PUT /products/:id/eaters
  def add_eater
    # @product.eaters.push(current_user)
    Eater.create(product_id: @product.id, user_id: current_user.id)
    @products = @event.products

    # redirect_to event_path(@event)
    prepare_for_form

    respond_to do |format|
      format.js { render template: '/products/show_table' }
    end
  end

  # DELETE /products/:id/eaters
  def delete_eater
    # @product.eaters.delete(current_user)
    Eater.where({ product_id: @product.id, user_id: current_user.id }).destroy_all
    @products = @event.products

    prepare_for_form
    #redirect_to event_path(@event)

    respond_to do |format|
      format.js { render template: '/products/show_table' }
    end
  end

  # GET /products/:id
  def show; end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.json { render json: @product, status: :ok }
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /products/:id/eaters
  def eaters
    # @eaters = User.joins('INNER JOIN eaters ON users.id = eaters.user_id')
    #               .where(eaters: {product_id: @product.id}).to_a.uniq

    @eaters = User.joins('INNER JOIN eaters ON users.id = eaters.user_id')
                   .where(eaters: {product_id: @product.id})
                   .select(:id, 'COUNT(users.id) as count').group(:id)
    @eaters_result = []
    @eaters.each do |eater|
      @eaters_result << {
        id: eater.id,
        count: eater.count,
        username: User.find_by_id(eater.id).username
      }
    end

    prepare_members

    @non_eaters = @members.difference(@eaters)     # Array of event members and not product eaters

    respond_to do |format|
      format.json { render status: :ok}
    end
  end

  # POST /products/:id/eaters
  def update_eaters
    eaters = params[:eaters]
    Eater.where({ product_id: @product.id }).destroy_all
    eaters.each do |eater|
      if eater[:count] && eater[:count] > 0
        (1..eater[:count]).each do |i|
          Eater.create(product_id: @product.id, user_id: eater[:id])
        end
      else
        Eater.create(product_id: @product.id, user_id: eater[:id])
      end
    end
    respond_to do |format|
      format.json { render json: { success: true }, status: :ok }
    end
  end

  private

  def set_product
    @product = Product.find_by_id(params[:id])
    @event = @product.event
  end

  def product_params
    params.fetch(:product, {}).permit(:name, :price, :buyer_id, :total, :event_id)
  end

  def prepare_for_form
    @product = Product.new
    prepare_members
  end

  def prepare_members
    @members = []
    unless @event.user.isQuest
      @members << @event.user
    end
    @members = (@members + @event.members.to_a).uniq
  end

  def add_eater_private(product, event)
    Eater.create(product_id: product.id, user_id: current_user.id)

    prepare_for_form
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_products.html.erb
<div class="row w-100" id="table">
  <div class="card">
    <div class="card-header">
      Продукты
    </div>
    <div class="card-body">
      <%= render 'events/products_form' %>
      <div  class="products-table_container">
        <table class="table">
          <thead>
          <tr>
            <% if user_signed_in? %>
              <td>Ты ел?</td>
            <% end %>
            <td>Продукт</td>
            <td>Цена</td>
            <td>К-во</td>
            <td>Купил</td>
            <td>Употребляло</td>
            <% if user_signed_in? %>
              <td>Ты съел (шт)</td>
<!--              <td>Ты употреблял?</td>-->
            <% end %>
            <td></td>
          </tr>
          </thead>
          <tbody>
          <% products.each do |product| %>

            <tr>
              <% if user_signed_in? %>
              <td>
                <% ate_total = Eater.where({product_id: product.id, user_id: current_user.id}).length %>
                  <%= check_box_tag 'ate', ate_total == 0, ate_total > 0,
                                    data: {
                                      remote: true,
                                      url: change_eater_path(product.id),
                                      method: :post
                                    } %>

                </td>
              <% end %>
              <td>
                <%= link_to product.name, product_path(product), class: 'link' %>
              </td>
              <td><%= product.price %></td>
              <td>
                <% if product.total %>
                  <%= product.total %>
                <% else %>
                  -
                <% end %>
              </td>
              <td><%= product.buyer.username %></td>
              <td class="tooltip">
                <%= Eater.where({product_id: product.id}).select(:user_id).distinct.length %> чел.
                <div class="tooltip-text">
                  <ul>
                    <% Eater.where({product_id: product.id}).select(:user_id).distinct.each do |eater| %>
                      <li>
                        <%= User.find(eater.user_id).username %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </td>
              <% if user_signed_in? %>
                <td>
                  <% if product.total %>
                    <%= ate_total %> шт.
                    <%=  link_to '(+1)', add_eater_path(product), class: 'link', method: :put, remote: true  %>
                  <% else %>
                    -
                  <% end %>
                </td>
<!--                <td>-->
                  <%# if ate_total == 0 %>
<!--                    Нет-->
                    <%#=  link_to ' (Изменить)', add_eater_path(product), class: 'link', method: :put, remote: true  %>
                  <%# elsif product.total %>
<!--                    Да  <%#=  link_to '(+1)', add_eater_path(product), class: 'link', method: :put, remote: true  %>-->
<!--                    /-->
                    <%#= link_to 'Нет', delete_eater_path(product), class: 'link', method: :delete, remote: true %>
                  <%# else %>
<!--                    Да-->
                    <%#= link_to ' (Изменить)', delete_eater_path(product), class: 'link', method: :delete, remote: true %>
                  <%# end %>
<!--                </td>-->
              <% end %>
              <td>
                <%= link_to product_path(product), method: :delete,
                            class: 'trash-link', remote: true do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer">
      <p class="products-total">
        Общая сумма: <strong><%= @products.sum(:price) %> </strong> руб.
      </p>
    </div>
  </div>
</div>

app/views/products/create.js.erb
document.getElementById('table').innerHTML = ("<%= j render 'products/products', products: @products %>")

app/views/products/show.html.erb
<div class="row w-100">
  <div class="card bg-gray1">
    <div class="row w-100 jc-sb">
      <h1 class="title events-title">
        <%= link_to event_path(@event), class: 'back-link' do %>
          <i class="fa-regular fa-circle-left"></i>
        <% end %>
        Информация о продукте
      </h1>
      <%= link_to 'Удалить', product_path(@product), class: 'title-link delete-link',
                  method: :delete
      %>
    </div>
  </div>
</div>

<div class="row w-100">
  <div class="card">
    <div class="card-body">
      <div class="product-container">
        <%= hidden_field_tag 'id', @product.id %>

        <div class="product-row">
          <p class="product-label">
            Название:
          </p>
          <div class="product-value">
            <%= text_field_tag 'name', @product.name, class: 'product-input', required: true %>
          </div>
        </div>

        <div class="product-row">
          <p class="product-label">
            Цена:
          </p>
          <div class="product-value">
            <%= number_field_tag 'price', @product.price, class: 'product-input' %>
          </div>
        </div>

        <div class="product-row">
          <p class="product-label">
            Количество:
          </p>
          <div class="product-value">
            <%= number_field_tag 'total', @product.total, class: 'product-input' %>
          </div>
        </div>

        <div class="product-row">
          <p class="product-label">
            Покупатель:
          </p>
          <div class="product-value">
            <%= text_field_tag 'buyer', @product.buyer.username, class: 'product-input', disabled: true %>
          </div>
        </div>

        <div class="product-row" id="eaters">

        </div>

      </div>

    </div>
  </div>
</div>





<%= javascript_pack_tag 'products/show' %>
<%= javascript_pack_tag 'products/eaters' %>

app/views/products/show_table.js.erb
document.getElementById('table').innerHTML = ("<%= j render 'products/products', products: @products %>")