config/routes.rb
Rails.application.routes.draw do
  get 'static/index'
  get 'profile/update'
  resources :events

  devise_for :users, exclude_routes: %w[edit_user_registration]

  #root to: 'events#index'
  #get '/index', to: 'static#index'
  root to: 'static#index'
  get '/welcome', to: 'static#welcome', as: 'welcome'

  resources :products, only: %i[create destroy show update]
  get '/products/:id/eaters', to: 'products#eaters'
  post '/products/:id/eaters', to: 'products#update_eaters'

  get '/join/:id', to: 'members#join', as: 'join'
  get '/leave/:id', to: 'members#leave', as: 'leave'
  delete '/leave/:id/:user_id', to: 'members#remove_member', as: 'remove_member'
  post '/bots/:id', to: 'members#add_bot', as: 'add_bot'

  put 'products/:id/eaters', to: 'products#add_eater', as: 'add_eater'
  delete 'products/:id/eaters', to: 'products#delete_eater', as: 'delete_eater'
  post 'products/:id/change_eater', to: 'products#change_eater', as: 'change_eater'
  # post '/products/complete', to: 'products#addition_complete', as: 'products_complete'

  get '/profile', to: 'profile#index', as: 'profile'
  post '/profile', to: 'profile#new'
  patch '/profile', to: 'profile#update'
  patch '/profile/password', to: 'profile#change_password', as: 'change_password'

  get '/events/:id/results', to: 'events#results', as: 'event_results'
  post '/events/:id/change_status', to: 'events#change_status', as: 'change_status'

  post '/quest', to: 'events#create_quest', as: 'quest'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_apple-touch-icons.html.erb
<% %w(57 72 76 114 120 144 152 167 180).each do |size| %>
  <%= favicon_link_tag "icons/apple-touch-icon-#{size}x#{size}.png",
                       rel: 'apple-touch-icon',
                       type: 'image/png',
                       sizes: "#{size}x#{size}" %>
  <%= favicon_link_tag "icons/apple-touch-icon-#{size}x#{size}-precomposed.png",
                       rel: 'apple-touch-icon-precomposed',
                       type: 'image/png',
                       sizes: "#{size}x#{size}" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="footer-text">
    Разработал А. Новиков
  </p>
  <p class="footer-text">
    2022 год
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <p class="header-title">
    <%= link_to root_path, class: "header-title" do %>
       <i class="fa-solid fa-users-gear"></i> Разделялка
    <% end %>
  </p>

  <a href="#" class="header-menu-show" id='header-menu-show'>
    <i class="fa-solid fa-bars"></i>
  </a>

  <nav class="header-menu" id="header-menu">
    <a href="#" class="header-menu-close" id="header-menu-close">
      <i class="fa-solid fa-xmark"></i>
    </a>
    <% if user_signed_in? %>
      <%= link_to current_user.username, profile_path, class: 'header-text' %>
      <%= link_to 'Выход', destroy_user_session_path, method: :delete, class: 'header-text' %>
    <% else %>
      <%= link_to 'Войти', new_user_session_path, class: 'header-text' %>
    <% end %>

  </nav>

</header>


<%= javascript_pack_tag 'header' %>

app/views/layouts/_toaster.html.erb
<div class="toaster-container">
  <% if notice %>
    <div class="toaster toaster-notice" id="notice">
      <%= notice %>
    </div>

    <script>
        const notice = document.getElementById("notice")
        setTimeout(() => {
            notice.style.display = 'none'
        }, 3000)
    </script>
  <% end %>

  <% if alert %>
    <div class="toaster toaster-alert" id="alert">
      <%= alert %>
    </div>

    <script>
        const alert = document.getElementById("alert")
        setTimeout(() => {
            alert.style.display = 'none'
        }, 3000)
    </script>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>Разделялка</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'users-gear-solid.svg', type: 'image/svg+xml', sizes: 'any' %>
    <%= render 'layouts/apple-touch-icons' %>
  </head>

  <body class="body">
    <%= render '/layouts/header' %>
    <main class="container">
      <%= yield %>
      <%= render '/layouts/toaster' %>
    </main>
    <%= render '/layouts/footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Разделялка</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'users-gear-solid.svg', type: 'image/svg+xml', sizes: 'any' %>
</head>

<body class="auth">
  <%= yield %>
</body>
</html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Разделялка</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'errors', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'users-gear-solid.svg', type: 'image/svg+xml', sizes: 'any' %>
  <%= render 'layouts/apple-touch-icons' %>
</head>

<body class="body">
  <div class="container">
    <%= link_to root_path, class: "title" do %>
      <i class="fa-solid fa-users-gear"></i> Разделялка
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/statics.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Разделялка</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'static', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/apple-touch-icons' %>
  <%= favicon_link_tag 'users-gear-solid.svg', type: 'image/svg+xml', sizes: 'any' %>
</head>

<body>
  <%= render 'static/header' %>
  <%= yield %>
  <%= render '/layouts/footer' %>
</body>
</html>